name: Build and Push images to Google Artifacts/Container Registry
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      PROJECT_ID: ${{ secrets.ARTIFACT_PROJECT_ID }}
      IMAGE_NAME: fitness-$GITHUB_RUN_NUMBER
      export_default_credentials: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    #- name: Automatic Tagging of Releases
    #  id: increment-git-tag
    #  run: |
    #    bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Build and push Docker images
      run: |
        docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/${{ env.IMAGE_NAME }}-workout-service:${{ github.sha }} -f WorkoutService/Dockerfile .
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/${{ env.IMAGE_NAME }}-workout-service:${{ github.sha }}

        docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/${{ env.IMAGE_NAME }}-nutrition-service:${{ github.sha }} -f NutritionService/Dockerfile .
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/${{ env.IMAGE_NAME }}-nutrition-service:${{ github.sha }}

        docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }} -f UserService/Dockerfile .
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }}
