name: Build and Push images to Google Artifacts/Container Registry
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      RUN_NUMBER: fitness-$GITHUB_RUN_NUMBER
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      PROJECT_ID: dls-exam
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        service_account: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}
    
    #- name: Automatic Tagging of Releases
    #  id: increment-git-tag 
    #  run: |
    #    bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Build and push Docker images
      run: |
        docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/images/${{ env.RUN_NUMBER }}-workout-service:${{ github.sha }} -f WorkoutService/Dockerfile .
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/${{ env.RUN_NUMBER }}-workout-service:${{ github.sha }}

        docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/images/${{ env.RUN_NUMBER }}-nutrition-service:${{ github.sha }} -f NutritionService/Dockerfile .
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/${{ env.RUN_NUMBER }}-nutrition-service:${{ github.sha }}

        docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/images/${{ env.RUN_NUMBER }}-user-service:${{ github.sha }} -f UserService/Dockerfile .
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/${{ env.RUN_NUMBER }}-user-service:${{ github.sha }}
